name: Build and deploy Node.js app to Azure Web App - drivercrashcourse-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: npm install - server
        run: |
          cd server
          npm install

      - name: npm install - client
        run: |
          cd client
          npm install
          npm run build
          cp -r ./build ../server/public
      
      - run: |
          zip -r drivercrashcourse-app.zip server
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: drivercrashcourse-app
          path: drivercrashcourse-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: drivercrashcourse-app
      - run: |
          unzip drivercrashcourse-app.zip
          rm drivercrashcourse-app.zip
      - name: Print Current Directory
        run: |
          echo "Current Directory: $(pwd)"
          ls -al
      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "drivercrashcourse-app"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_45995785BB1E4B878C80177B6D23F7D8 }}
          package: .
